from __future__ import annotations

from abc import ABC
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Sequence, Union


class SignalDirection(str, Enum):
    """
    Strategy signal direction.
    """

    LONG = "long"
    SHORT = "short"
    FLAT = "flat"
    HOLD = "hold"
    
@dataclass(slots=True)
class StrategySignal:
    """
    Signal generated by strategy.

    This only represents strategy opinion.
    It is not an order.
    """

    strategy_name: str
    symbol: str
    direction: SignalDirection
    score: float = 0.0
    confidence: float = 0.0
    reason: str = ""
    extra: dict[str, Any] = field(default_factory=dict)
    
@dataclass(slots=True)
class TargetPosition:
    """
    Target position generated by strategy.

    This represents the desired portfolio weight.
    It is not an order.
    """

    strategy_name: str
    symbol: str
    target_weight: float
    score: float = 0.0
    reason: str = ""
    extra: dict[str, Any] = field(default_factory=dict)
    
@dataclass(slots=True)
class StrategyContext:
    """
    Runtime context passed to strategy.

    Strategy can read data and services from context,
    but should not send orders directly.
    """

    now: Any = None
    bar_cache: Any = None
    factor_engine: Any = None
    account: Any = None
    positions: Any = None
    universe: Sequence[str] | None = None
    params: dict[str, Any] = field(default_factory=dict)